# -*- coding: utf-8 -*-
"""Group12_Credit_Card_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13CBajVIRWp6nVpx6_Sy8aKXUCfAEvMUD

# STEP 1: DATA CLEANING

###
1. IMPORTING LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""###
2. LOADING DATASET
"""

df = pd.read_csv('creditcard.csv')

df.head()

"""###
3. INSPECTING DATASET
"""

# There are 41683 rows and 31 columns in our dataset
df.shape

# dtpyes and non-null columns

df.describe().T

# There is no null value in our dataset
df.info()

"""###
4. REMOVING DUPLICATE ROWS
"""

# Remove duplicates

# There are 181 duplicate data

df.duplicated().sum()

df.drop_duplicates(inplace=True)

# There are now no duplicate data

print("Confirm all duplicates removed:", df.duplicated().sum())

print("After removing duplicates:", df.shape)

"""###
5. HANDLING MISSING VALUES
"""

# Checking null values
print("Missing values:", df.isnull().sum())

# Find which columns have nulls
print(df.isnull().sum()[df.isnull().sum() > 0])

df['Amount'].fillna(df['Amount'].median(), inplace=True)

# Fill with 0 - these are PCA features, 0 means "at the mean"
df.fillna(0,inplace=True)

print("Missing values after fix:" , df.isnull().sum().sum())

"""# STEP 2: EXPLORATORY DATA ANALYSIS

### 1. DISTRIBUTION PLOT FOR TRANSACTION AMOUNT
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Amount'])
plt.title('Distribution Plot for Transaction Amount')
plt.xlabel('Transaction Amount')
plt.ylabel('Frequency')
plt.show()

"""### 2. DISTRIBUTION PLOT FOR TIME FEATURE"""

plt.figure(figsize=(8,5))
sns.histplot(df['Time'], bins=50, kde=True)
plt.title('Distribution of Transactions Time')
plt.xlabel('Time')
plt.ylabel('Frequency')
plt.show()

"""### 3. COUNT PLOT FOR FRAUD Vs NON FRAUD TRANSACTIONS"""

plt.figure(figsize=(6,4))
sns.countplot(x='Class', data=df)
plt.title('Count of Fraudulent Vs Non-Fraud Transactions')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks([0, 1], ['Non-Fraud', 'Fraud'])
plt.show()

"""### 4. CORRELATION HEATMAP"""

plt.figure(figsize=(18,12))
correlation= df.corr()
sns.heatmap(correlation, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""### 5. DISTRIBUTION OF FRAUDULENT AND NON FRAUDULENT TRANSACTIONS"""

fraud = df[df['Class'] == 1]
non_fraud = df[df['Class'] == 0]
plt.figure(figsize=(10,5))
sns.histplot(fraud['Amount'], bins=30, kde=True, label='Fraud', color='red', alpha= 0.6)
sns.histplot(non_fraud['Amount'], bins=30, kde=True, label='Non-Fraud', color='green', alpha=0.6)
plt.title('Distribution of Fraudulent and Non-Fraudulent Transactions amounts')
plt.xlabel('Transaction Amount')
plt.ylabel('Frequency')
plt.legend()
plt.show()

"""# STEP 3: DATA PREPROCESSING

###
1. IMPORTING LIBRARIES
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE

"""###
2. SPLITTING FEATURES AND TARGET
"""

x = df.drop("Class", axis =1)
y = df["Class"]

"""###
3. TRAIN-TEST SPLIT
"""

# made use of 80:20 ratio with stratifying to preserve the same class ratio in the training and testing set.
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2,stratify=y, random_state=42)

print("Before SMOTE:")
print("Non-Fraud:", sum(y_train == 0))
print("Fraud:", sum(y_train == 1))

smote = SMOTE(random_state=42)
x_train, y_train = smote.fit_resample(x_train, y_train)

print("After SMOTE:")
print("Non-Fraud:", sum(y_train == 0))
print("Fraud:", sum(y_train == 1))

"""###
4. FEATURE SCALING
"""

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)   # fit on training data only
x_test_scaled  = scaler.transform(x_test)          # only transform test data, never fit

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

"""#STEP 4: MODELLING

###
1. MODEL 1: LOGISTIC REGRESSION
"""

model_lr = LogisticRegression(max_iter=1000)

model_lr.fit(x_train_scaled, y_train)

"""###
PREDICTIONS
"""

y_pred_lr = model_lr.predict(x_test_scaled)

"""###
2. MODEL 2: RANDOM FOREST CLASSIFIER
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train_scaled, y_train)

"""###
PREDICTIONS
"""

y_pred_rf = rf_model.predict(x_test_scaled)

"""###
3. EVALUATIONS

A. LOGISTIC REGRESSION EVALUATION
"""

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

"""###
B. CONFUSION MATRIX
"""

print("Confusion:", confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

sns.heatmap(confusion_matrix(y_test, y_pred_lr), annot=True, fmt='d', cmap='Blues')
plt.title('Logistic Regression Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""###
C. RANDOM FOREST EVALUATION
"""

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

"""###
D. RANDOM FOREST CONFUSION MATRIX
"""

print("Confusion:" , confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

sns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt='d', cmap='Blues')
plt.title('Random Forest Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""# STEP 5 : BUILDING A NEURAL NETWORK"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

"""#### A. BUILD THE MODEL"""

model = keras.Sequential([
    layers.Input(shape=(x_train_scaled.shape[1],)),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(32, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(1, activation="sigmoid")
])
model.summary()

"""####B. COMPILE THE MODEL"""

model.compile(
    optimizer="adam",
    loss="binary_crossentropy", #
    metrics=["accuracy","AUC","Precision", "Recall"],  # AUC measures how well the model separates frud from non fraud
)

"""#### C. TRAIN NEURAL NETWORK"""

history = model.fit(
    x_train_scaled, y_train,
    epochs=15,
    batch_size=128,
    validation_split=0.1,
    verbose=1,
)

"""#### D. VISUALIZE LOSS AND ACCURACY"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Loss curves
ax1.plot(history.history["loss"],     label="Training Loss",   linewidth=2)
ax1.plot(history.history["val_loss"], label="Validation Loss", linewidth=2, linestyle="--")
ax1.set_title("Loss over Epochs", fontweight="normal")
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Loss")
ax1.legend()
ax1.grid(True, alpha=0.3)

# Accuracy curves
ax2.plot(history.history["accuracy"],     label="Training Accuracy",   linewidth=2)
ax2.plot(history.history["val_accuracy"], label="Validation Accuracy", linewidth=2, linestyle="--")
ax2.set_title("Accuracy over Epochs", fontweight="normal")
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Accuracy")
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.suptitle("Training History", fontsize=14, fontweight="normal")
plt.tight_layout()
plt.show()

"""#### E. EVALUATE ON TEST SET"""

loss,accuracy, auc, precision, recall= model.evaluate(x_test_scaled, y_test, verbose=0)

print(f"Test Loss     : {loss:.4f}")
print(f"Test Accuracy : {accuracy* 100:.2f}%")
print(f"AUC: {auc:.4f}")
print(f"Test Precision: {precision:.4f}")
print(f"Test Recall: {recall:.4f}")

"""#### F. CLASSIFICATION REPORT"""

y_pred_probs = model.predict(x_test_scaled, verbose=0)
y_pred = np.round(y_pred_probs). flatten().astype(int)

print("Classification Report")
print("=" * 60)
print(classification_report(
    y_test,
    y_pred,
    target_names=["Non-Fraud","Fraud"],
    zero_division=0
))

"""#### G. CONFUSION MATRIX"""

print("Confusion:", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#save neural network model
model.save("credit_card_fraud_detection_model.keras")

#save scaler
import pickle
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

from google.colab import files
files.download("credit_card_fraud_detection_model.keras")
files.download("scaler.pkl")

requirements = """streamlit>=1.35.0
pandas>=2.0.0
numpy>=1.24.0
matplotlib>=3.7.0
seaborn>=0.12.0
scikit-learn>=1.3.0
imbalanced-learn>=0.11.0
tensorflow>=2.13.0"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

from google.colab import files
files.download('requirements.txt')